### PR TITLE
Convert the README to rst

### PR DESCRIPTION
**Pull request by cjbayliss**
I found it a little hard to read the README on github, so I converted it to reStructuredText.

I also fixed some spelling and grammar.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
Thanks for the pull request Christopher. This looks good to me.

@definite Could you please review this and merge if you agree?

**Comment by seanf** [comment]
In the rendered preview, all the command samples ("code") seem to be in `<blockquote><code>` which is a little odd.

**Comment by seanf** [comment]
@cjbayliss Perhaps the indented code doesn't need to be surrounded with  "``"?  (Not sure of my RST, but I'm assuming it's somewhat similar to markdown in this respect.)

**Comment by seanf** [comment]
I think what I suggested above will work, if the preceding paragraphs end in two colons, like this::

http://sphinx-doc.org/rest.html#source-code

**Comment by cjbayliss** [comment]
Yep, that works better, I'll make the change now.

**Comment by seanf** [comment]
Anyone wanting to see the preview, see here: https://github.com/cjbayliss/zanata-python-client/blob/master/README.rst

**Comment by seanf** [comment]
@definite Are you happy with the changes?

**Comment by seanf** [comment]
I generally prefer markdown to RST, but RST probably makes sense for a Python project, and it wouldn't be difficult to convert the formatting from .rst to .md if we need to.

**Comment by cjbayliss** [comment]
Yep. I should learn markdown, I just do RST because that is what we use at Cyber IT Solutions. :)

**Comment by seanf** [comment]
Looks like the `.. Note::` rendering is being messed up by this: https://github.com/github/markup/issues/68

I think we'll just have to live with it.

**Comment by definite** [comment]
The rest looks fine to me.

**Comment by cjbayliss** [comment]
I have made that change, I don't know if there are more like that because I don't use Zanata myself. It is probably worth getting someone to got through this README and fix up that sort of stuff. I only converted the README from what it was to rst. :)

**Comment by seanf** [comment]
Thanks for the contribution, @cjbayliss .

**Comment by cjbayliss** [comment]
No problem! :)

**Pull request merged**
